### ISSUE TITLE
 Status 403 - Toegang geweigerd

### ISSUE THREAD

**Issue by Sarnog** [sanderdw/Dutch-Gas-prices-API#6]
or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
Log level is set to INFO
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[15:53:12] INFO: Log_level: info
[15:53:12] INFO: mqtt_host: 192.168.1.52
[15:53:12] INFO: mqtt_port: 1883
[15:53:12] INFO: Starting dutch gas prices...
[2024-02-01 15:53:14] INFO    : DGP initialized, launching client
[2024-02-01 15:53:14] INFO    : Connecting to mqtt host '192.168.1.52' with clientname 'f5a8083e-dutch-gas-prices'
[2024-02-01 15:53:14] INFO    : Using username 'mqtt-user' to connect to '192.168.1.52'
[2024-02-01 15:53:14] INFO    : Connected with result code '0'
[2024-02-01 15:54:05] INFO    : Received payload '{"station_id":4121,"fuel_type":"euro95","friendly_name_template":"[brand] ([station_street])"}' on topic 'dgp/gas_station'
[2024-02-01 15:54:05] ERROR   : _write_stationdata '4121': statuscode '403'
[2024-02-01 15:54:05] ERROR   : _write_stationdata '4121': Used header '{'Accept': '*/*', 'Connection': 'keep-alive', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.75 Safari/537.36 OPR/54.0.2952.64'}'
[2024-02-01 15:54:05] ERROR   : _write_stationdata '4121': Used IP ''
[2024-02-01 15:54:05] ERROR   : _write_stationdata '4121': Response text '<html><head><title>Apache Tomcat/7.0.76 - Error report</title><style></style> </head><body><h1>HTTP Status 403 - Toegang geweigerd; mail naar tankservice-block@app-it-up.com voor vragen</h1><HR size="1" noshade="noshade"><p><b>type</b> Status report</p><p><b>message</b> <u>Toegang geweigerd; mail naar tankservice-block@app-it-up.com voor vragen</u></p><p><b>description</b> <u>Access to the specified resource has been forbidden.</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/7.0.76</h3></body></html>'
[2024-02-01 15:54:05] ERROR   : _write_allstationdata: statuscode '403'
[2024-02-01 15:54:05] ERROR   : _write_allstationdata: Used header '{'Accept': '*/*', 'Connection': 'keep-alive', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.75 Safari/537.36 OPR/54.0.2952.64'}'
[2024-02-01 15:54:06] ERROR   : _write_allstationdata: Used IP ''
[2024-02-01 15:54:06] ERROR   : _write_allstationdata: Response text '<html><head><title>Apache Tomcat/7.0.76 - Error report</title><style></style> </head><body><h1>HTTP Status 403 - Toegang geweigerd; mail naar tankservice-block@app-it-up.com voor vragen</h1><HR size="1" noshade="noshade"><p><b>type</b> Status report</p><p><b>message</b> <u>Toegang geweigerd; mail naar tankservice-block@app-it-up.com voor vragen</u></p><p><b>description</b> <u>Access to the specified resource has been forbidden.</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/7.0.76</h3></body></html>'
[2024-02-01 15:54:06] INFO    : publishing station_id None to mqtt
Exception in thread Thread-1 (publish_station):
[2024-02-01 15:54:06] INFO    : Received payload '{"station_id":4121,"fuel_type":"euro98","friendly_name_template":"[brand] ([station_street])"}' on topic 'dgp/gas_station'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/mqtt_client.py", line 174, in publish_station
    stationtopic = f"{station_info['station_id']}_{station_info['fuel_type']}"
                                                   ~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'fuel_type'
[2024-02-01 15:54:06] ERROR   : _write_stationdata '4121': statuscode '403'
[2024-02-01 15:54:06] ERROR   : _write_stationdata '4121': Used header '{'Accept': '*/*', 'Connection': 'keep-alive', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.75 Safari/537.36 OPR/54.0.2952.64'}'
[2024-02-01 15:54:07] ERROR   : _write_stationdata '4121': Used IP ''
[2024-02-01 15:54:07] ERROR   : _write_stationdata '4121': Response text '<html><head><title>Apache Tomcat/7.0.76 - Error report</title><style><!--H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}HR {color : #525D76;}--></style> </head><body><h1>HTTP Status 403 - Toegang geweigerd; mail naar tankservice-block@app-it-up.com voor vragen</h1><HR size="1" noshade="noshade"><p><b>type</b> Status report</p><p><b>message</b> <u>Toegang geweigerd; mail naar tankservice-block@app-it-up.com voor vragen</u></p><p><b>description</b> <u>Access to the specified resource has been forbidden.</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/7.0.76</h3></body></html>'
[2024-02-01 15:54:07] ERROR   : _write_allstationdata: statuscode '403'
[2024-02-01 15:54:07] ERROR   : _write_allstationdata: Used header '{'Accept': '*/*', 'Connection': 'keep-alive', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.75 Safari/537.36 OPR/54.0.2952.64'}'
[2024-02-01 15:54:07] ERROR   : _write_allstationdata: Used IP ''
[2024-02-01 15:54:07] ERROR   : _write_allstationdata: Response text '<html><head><title>Apache Tomcat/7.0.76 - Error report</title><style><!--H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}HR {color : #525D76;}--></style> </head><body><h1>HTTP Status 403 - Toegang geweigerd; mail naar tankservice-block@app-it-up.com voor vragen</h1><HR size="1" noshade="noshade"><p><b>type</b> Status report</p><p><b>message</b> <u>Toegang geweigerd; mail naar tankservice-block@app-it-up.com voor vragen</u></p><p><b>description</b> <u>Access to the specified resource has been forbidden.</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/7.0.76</h3></body></html>'
[2024-02-01 15:54:07] INFO    : publishing station_id None to mqtt
Exception in thread Thread-2 (publish_station):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
[2024-02-01 15:54:07] INFO    : Received payload '{"station_id":4121,"fuel_type":"diesel","friendly_name_template":"[brand] ([station_street])"}' on topic 'dgp/gas_station'
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/mqtt_client.py", line 174, in publish_station
    stationtopic = f"{station_info['station_id']}_{station_info['fuel_type']}"
                                                   ~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'fuel_type'
[2024-02-01 15:54:07] ERROR   : _write_stationdata '4121': statuscode '403'
[2024-02-01 15:54:07] ERROR   : _write_stationdata '4121': Used header '{'Accept': '*/*', 'Connection': 'keep-alive', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.75 Safari/537.36 OPR/54.0.2952.64'}'
[2024-02-01 15:54:08] ERROR   : _write_stationdata '4121': Used IP ''
[2024-02-01 15:54:08] ERROR   : _write_stationdata '4121': Response text '<html><head><title>Apache Tomcat/7.0.76 - Error report</title><style><!--H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}HR {color : #525D76;}--></style> </head><body><h1>HTTP Status 403 - Toegang geweigerd; mail naar tankservice-block@app-it-up.com voor vragen</h1><HR size="1" noshade="noshade"><p><b>type</b> Status report</p><p><b>message</b> <u>Toegang geweigerd; mail naar tankservice-block@app-it-up.com voor vragen</u></p><p><b>description</b> <u>Access to the specified resource has been forbidden.</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/7.0.76</h3></body></html>'
[2024-02-01 15:54:08] ERROR   : _write_allstationdata: statuscode '403'
[2024-02-01 15:54:08] ERROR   : _write_allstationdata: Used header '{'Accept': '*/*', 'Connection': 'keep-alive', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.75 Safari/537.36 OPR/54.0.2952.64'}'
[2024-02-01 15:54:09] ERROR   : _write_allstationdata: Used IP ''
[2024-02-01 15:54:09] ERROR   : _write_allstationdata: Response text '<html><head><title>Apache Tomcat/7.0.76 - Error report</title><style><!--H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}HR {color : #525D76;}--></style> </head><body><h1>HTTP Status 403 - Toegang geweigerd; mail naar tankservice-block@app-it-up.com voor vragen</h1><HR size="1" noshade="noshade"><p><b>type</b> Status report</p><p><b>message</b> <u>Toegang geweigerd; mail naar tankservice-block@app-it-up.com voor vragen</u></p><p><b>description</b> <u>Access to the specified resource has been forbidden.</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/7.0.76</h3></body></html>'
[2024-02-01 15:54:09] INFO    : publishing station_id None to mqtt
Exception in thread Thread-3 (publish_station)[2024-02-01 15:54:09] INFO    : Received payload '{"station_id":4121,"fuel_type":"lpg","friendly_name_template":"[brand] ([station_street])"}' on topic 'dgp/gas_station'
:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/mqtt_client.py", line 174, in publish_station
    stationtopic = f"{station_info['station_id']}_{station_info['fuel_type']}"
                                                   ~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'fuel_type'
[2024-02-01 15:54:09] ERROR   : _write_stationdata '4121': statuscode '403'
[2024-02-01 15:54:09] ERROR   : _write_stationdata '4121': Used header '{'Accept': '*/*', 'Connection': 'keep-alive', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.75 Safari/537.36 OPR/54.0.2952.64'}'
[2024-02-01 15:54:09] ERROR   : _write_stationdata '4121': Used IP ''
[2024-02-01 15:54:09] ERROR   : _write_stationdata '4121': Response text '<html><head><title>Apache Tomcat/7.0.76 - Error report</title><style><!--H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}HR {color : #525D76;}--></style> </head><body><h1>HTTP Status 403 - Toegang geweigerd; mail naar tankservice-block@app-it-up.com voor vragen</h1><HR size="1" noshade="noshade"><p><b>type</b> Status report</p><p><b>message</b> <u>Toegang geweigerd; mail naar tankservice-block@app-it-up.com voor vragen</u></p><p><b>description</b> <u>Access to the specified resource has been forbidden.</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/7.0.76</h3></body></html>'
[2024-02-01 15:54:09] ERROR   : _write_allstationdata: statuscode '403'
[2024-02-01 15:54:09] ERROR   : _write_allstationdata: Used header '{'Accept': '*/*', 'Connection': 'keep-alive', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.75 Safari/537.36 OPR/54.0.2952.64'}'
[2024-02-01 15:54:10] ERROR   : _write_allstationdata: Used IP ''
[2024-02-01 15:54:10] ERROR   : _write_allstationdata: Response text '<html><head><title>Apache Tomcat/7.0.76 - Error report</title><style><!--H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}HR {color : #525D76;}--></style> </head><body><h1>HTTP Status 403 - Toegang geweigerd; mail naar tankservice-block@app-it-up.com voor vragen</h1><HR size="1" noshade="noshade"><p><b>type</b> Status report</p><p><b>message</b> <u>Toegang geweigerd; mail naar tankservice-block@app-it-up.com voor vragen</u></p><p><b>description</b> <u>Access to the specified resource has been forbidden.</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/7.0.76</h3></body></html>'
[2024-02-01 15:54:10] INFO    : publishing station_id None to mqtt
Exception in thread Thread-4 (publish_station):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/mqtt_client.py", line 174, in publish_station
    stationtopic = f"{station_info['station_id']}_{station_info['fuel_type']}"
                                                   ~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'fuel_type

**Comment by Keesiej** [comment]
Same issue for me here.

**Comment by Hurr1c4n3** [comment]
Got the same issue. Also tried to stop the add-on for a few hours and activated again, but still the same error message.

**Comment by martincijsouw** [comment]
Same issue here, i guess they blocked pull requests somehow from theyr site. 
Maybe its the 5min pull frequency, not sure whats changed in the leaseplan web config.

**Comment by JeroenvanA** [comment]
They blocked our ip addresses

**Comment by martincijsouw** [comment]
I asked them to unblock my IP. They won't :(
